"""Provider-neutral exchange adapter contract."""
from abc import ABC, abstractmethod
from decimal import Decimal
from .models import NormalizedBalance, NormalizedPosition, NormalizedOrder, OrderSide

class ExchangeAdapter(ABC):
    venue: str
    @abstractmethod
    def health(self) -> bool: ...
    @abstractmethod
    def balances(self) -> list[NormalizedBalance]: ...
    @abstractmethod
    def positions(self) -> list[NormalizedPosition]: ...
    @abstractmethod
    def place_order(self, symbol: str, side: OrderSide, quantity: Decimal, price: Decimal | None = None) -> NormalizedOrder: ...
    @abstractmethod
    def cancel_order(self, order_id: str) -> bool: ...
    @abstractmethod
    def get_order(self, order_id: str) -> NormalizedOrder: ...
    @abstractmethod
    def fees(self, symbol: str) -> Decimal: ...
